services:
  web: &php
    image: tissue-dev-web
    build:
      context: .
      dockerfile: docker/development/web.dockerfile
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    networks:
      - backend
    ports:
      - 4545:80
    restart: always
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: tissue
      POSTGRES_USER: tissue
      POSTGRES_PASSWORD: tissue
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend
    restart: always
  scheduler:
    <<: *php
    command: php artisan schedule:work
    ports: []
  front:
    image: tissue-dev-web
    command: sh -c "yarn && yarn dev --host --port 4546"
    env_file:
      - .env
    volumes:
      - .:/var/www/html
      - front_node_modules:/var/www/html/node_modules
    ports:
      - 4546:4546
    restart: always
    depends_on:
      - web
  antlr:
    image: tissue-antlr:4.13.1
    build:
      context: .
      dockerfile: docker/development/antlr.dockerfile
    volumes:
      - .:/app
    working_dir: /app
    profiles:
      - utility

networks:
  backend:

volumes:
  db:
  front_node_modules:
