services:
  web:
    build:
      context: .
      dockerfile: docker/development/web.dockerfile
    env_file:
      - .env
    volumes:
      - .:/var/www/html
    networks:
      - backend
    ports:
      - 4545:80
    restart: always
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: tissue
      POSTGRES_USER: tissue
      POSTGRES_PASSWORD: tissue
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - backend
    restart: always
  antlr:
    build:
      context: .
      dockerfile: docker/development/antlr.dockerfile
    volumes:
      - .:/app
    working_dir: /app
    profiles:
      - utility

networks:
  backend:

volumes:
  db:
